<a href="https://colab.research.google.com/github/Franchertz/PortfolioProjects/blob/main/Numerical_Python(NumPy)_Part2ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Numpy: Generating Random Values**

**with <np.random.rand>**

#Example: *Creating an array of a given shape and populating with random samples form a uniform distribution between 0 and 1*

In [9]:
import numpy as np

In [14]:
np.random.rand(3,2)

array([[0.36873788, 0.03643588],
       [0.5761742 , 0.67772736],
       [0.12800143, 0.34322226]])

In [17]:
np.random.rand(5,3)

array([[0.20996734, 0.18291374, 0.69065458],
       [0.23476411, 0.84468728, 0.97579136],
       [0.493457  , 0.5374894 , 0.04893742],
       [0.28448251, 0.46257101, 0.23203518],
       [0.0572425 , 0.19900911, 0.59224405]])

**with <np.random.rand>**

In [23]:
a = np.random.randn(3,3) #Returns sample from the "standard normal" distribution
a

array([[-0.5501054 ,  0.83530375, -0.3671542 ],
       [ 0.27087073,  0.69479907,  1.05792263],
       [-1.23820189,  0.61202913, -0.59685642]])

**with <np.random.randint>**

In [35]:
#Generating 10 numbers between 4 and 15
mn=np.random.randint(4,15,10)
mn

array([14,  7,  9, 10,  9,  6, 11,  6,  4,  7])

In [36]:
len(mn)

10

In [37]:
mn.reshape(5,2)

array([[14,  7],
       [ 9, 10],
       [ 9,  6],
       [11,  6],
       [ 4,  7]])

In [38]:
tt = np.random.randint(0,10, (4,3))
tt

array([[3, 0, 6],
       [6, 5, 2],
       [1, 2, 5],
       [4, 8, 4]])